name: Generate PDFs

on:
  push:
    paths:
      - "**-overview.md"
      - "**-quick-start.md"
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        sbc: [raspi, rockpi]
        variant: [indoor, outdoor]
        file: [overview, quick-start]
        exclude:
          - sbc: rockpi
            variant: outdoor

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate PDFs (Non RasPi)
        if: matrix.sbc != 'raspi'
        uses: docker://pandoc/latex:2.9
        with:
          entrypoint: pdf-gen/gen-pdfs.sh
          args: >-
            pdf-gen/pdf-data.yml
            docs/${{ matrix.variant }}-${{ matrix.sbc }}-hotspot/${{ matrix.file }}.md
            -o docs/pdfs/${{ matrix.variant }}-${{ matrix.sbc }}-${{ matrix.file }}.pdf
            --pdf-engine=xelatex
            --resource-path docs/media/

      - name: Generate PDFs (RasPi)
        if: matrix.sbc == 'raspi'
        uses: docker://pandoc/latex:2.9
        with: 
          entrypoint: pdf-gen/gen-pdfs.sh
          args: >-
            pdf-gen/pdf-data.yml
            docs/${{ matrix.variant }}-hotspot/${{ matrix.file }}.md
            -o docs/pdfs/${{ matrix.variant }}-${{ matrix.file }}.pdf
            --pdf-engine=xelatex
            --resource-path docs/media/

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: pdf-artifacts
          path: docs/pdfs/*.pdf

      - name: Update PDFs on repo (Non RasPi)
        if: matrix.sbc != 'raspi'
        uses: EndBug/add-and-commit@v8
        with:
          message: Update ${{ matrix.sbc }} ${{ matrix.variant }} ${{ matrix.file }} PDF
          add: "-A"

      - name: Update PDFs on repo (RasPi)
        if: matrix.sbc == 'raspi'
        uses: EndBug/add-and-commit@v8
        with:
          message: Update ${{ matrix.sbc }} ${{ matrix.variant }} ${{ matrix.file }} PDF
          add: "-A"
