name: Generate PDFs

on:
  schedule:
    - cron:  "15 0 * * *" # Run daily at 00.15
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        sbc: [raspi, rockpi]
        variant: [indoor, outdoor]
        file: [overview, quick-start]
        exclude:
          - sbc: rockpi
            variant: outdoor

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          ref: main

      - name: Generate PDFs (Non RasPi)
        if: matrix.sbc != 'raspi'
        uses: docker://pandoc/latex:2.9
        with:
          entrypoint: pdf-gen/gen-pdfs.sh
          args: >-
            pdf-gen/pdf-data.yml
            docs/${{ matrix.variant }}-${{ matrix.sbc }}-hotspot/${{ matrix.file }}.md
            -o docs/pdfs/${{ matrix.variant }}-${{ matrix.sbc }}-${{ matrix.file }}.pdf
            --pdf-engine=xelatex
            --resource-path docs/media/

      - name: Generate PDFs (RasPi)
        if: matrix.sbc == 'raspi'
        uses: docker://pandoc/latex:2.9
        with: 
          entrypoint: pdf-gen/gen-pdfs.sh
          args: >-
            pdf-gen/pdf-data.yml
            docs/${{ matrix.variant }}-hotspot/${{ matrix.file }}.md
            -o docs/pdfs/${{ matrix.variant }}-${{ matrix.file }}.pdf
            --pdf-engine=xelatex
            --resource-path docs/media/

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: pdf-artifacts
          path: docs/pdfs/*.pdf

      - name: Update PDFs on repo (Non RasPi)
        if: matrix.sbc != 'raspi'
        uses: test-room-7/action-update-file@v1
        with:
          branch: main
          file-path: docs/pdfs/${{ matrix.variant }}-${{ matrix.sbc }}-${{ matrix.file }}.pdf
          commit-msg: Update ${{ matrix.sbc }} ${{ matrix.variant }} ${{ matrix.file }} PDF
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PDFs on repo (RasPi)
        if: matrix.sbc == 'raspi'
        uses: test-room-7/action-update-file@v1
        with:
          branch: main
          file-path: docs/pdfs/${{ matrix.variant }}-${{ matrix.file }}.pdf
          commit-msg: Update ${{ matrix.sbc }} ${{ matrix.variant }} ${{ matrix.file }} PDF
          github-token: ${{ secrets.GITHUB_TOKEN }}
