name: Generate PDFs

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - uses: docker://pandoc/latex:2.9
        with:
          args: /pdf-gen/pdf-data.yml  /docs/indoor-hotspot/overview.md -o /docs/pdfs/indoor-overview.pdf --pdf-engine=xelatex --resource-path /docs/media/
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: docs/pdfs/
